/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package blocks;

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;

/**
 *
 * @author Administrator
 */
public class GameBoardPanel extends javax.swing.JPanel {

    
    GameBoard pGameBoard;   /* ゲームボードへのポインタ */
    
    public void setGameBoard(GameBoard ptr){
        pGameBoard = ptr;
    }
    
    
    /**
     * Creates new form GameBoardPanel
     */
    public GameBoardPanel() {
        initComponents();
    }
    
    
    @Override
    public void paintComponent(Graphics g){
       if(pGameBoard==null) return;
        
        
        int width = this.getWidth();//this.getContentPane().getWidth();
        int height = this.getHeight();//this.getContentPane().getHeight();
        int sizeX = width / GameBoard.BOARD_X;
        int sizeY = height / GameBoard.BOARD_Y;
        
        final Font font = new Font("Arial", Font.BOLD, 10);
        
        g.setColor(Color.GRAY);
        g.drawRect(0, 0, width, height);
        
        for(int i=0; i<GameBoard.BOARD_Y; i++){
            for(int j=0; j<GameBoard.BOARD_X; j++){
                int owner = pGameBoard.getOwner(j, i);
                g.setColor(Player.id2Color(owner));
                g.fillRect(j*sizeX, i*sizeY, sizeX-2, sizeY-2);
            }
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
